#### Case Statement.

In [377]:
!pip install apriori-python

Requirement already satisfied: apriori-python in c:\users\jalee\anaconda3\lib\site-packages (1.0.4)

In [378]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sqlalchemy import create_engine

# Prepare Data.

In [379]:
def db_connect():
    username = 'postgres'
    password = ''
    host = 'localhost'
    port = 5432  # Default PostgreSQL port is 5432
    database = 'postgres'
    # Create connection string and engine
    connection_string = f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}'
    engine = create_engine(connection_string)

    # Query Exection.
    query = 'SELECT * FROM CUSTOMER;'

    return engine,query

In [380]:
# Call the function to get the engine and query
engine, query = db_connect()

In [381]:
df = pd.read_sql(query, engine)
# Display the DataFrame
df.head()

,customer_id,first_name,last_name,phone_num,item_1,item_2,item_3,item_4
0,5,rl,wl,734343,CARBATTERY_5,CHARPORT_5,ELECTRIC_BIKE_MOD_5,CAMERA_MODX5
1,7,ELN,TSA,3434453,CARBATTERY_7,CHARPORT_5,ELECTRIC_BIKE_MOD_7,CAMERA_MODX7
2,8,PUT,NN,3434452,CARBATTERY_8,CHARPORT_8,ELECTRIC_BIKE_MOD_8,CAMERA_MODX8
3,9,UKR,KGN,3434456,CARBATTERY_9,CHARPORT_9,ELECTRIC_BIKE_MOD_9,CAMERA_MODX9
4,10,GY,EU,3434456,CARBATTERY_10,CHARPORT_10,ELECTRIC_BIKE_MOD_10,CAMERA_MODX10

In [382]:
df.shape

(20, 8)

In [383]:
df.describe()

       customer_id     phone_num
count     20.00000  2.000000e+01
mean       9.65000  1.028667e+07
std        5.69649  1.977509e+07
min        1.00000  7.343410e+05
25%        4.75000  2.759425e+06
50%        9.50000  3.434453e+06
75%       14.25000  9.612311e+06
max       19.00000  8.434356e+07

In [384]:
# Converting the data into CSV file.
df.to_csv('cars_dataset.csv')

In [385]:
df

,customer_id,first_name,last_name,phone_num,item_1,item_2,item_3,item_4
0,5,rl,wl,734343,CARBATTERY_5,CHARPORT_5,ELECTRIC_BIKE_MOD_5,CAMERA_MODX5
1,7,ELN,TSA,3434453,CARBATTERY_7,CHARPORT_5,ELECTRIC_BIKE_MOD_7,CAMERA_MODX7
2,8,PUT,NN,3434452,CARBATTERY_8,CHARPORT_8,ELECTRIC_BIKE_MOD_8,CAMERA_MODX8
3,9,UKR,KGN,3434456,CARBATTERY_9,CHARPORT_9,ELECTRIC_BIKE_MOD_9,CAMERA_MODX9
4,10,GY,EU,3434456,CARBATTERY_10,CHARPORT_10,ELECTRIC_BIKE_MOD_10,CAMERA_MODX10
5,11,KS,A,3434451,CARBATTERY_11,CHARPORT_11,ELECTRIC_BIKE_MOD_11,CAMERA_MODX11
6,12,NG,AAF,3434452,CARBATTERY_12,CHARPORT_12,ELECTRIC_BIKE_MOD_12,CAMERA_MODX12
7,13,KK,MKK,3434453,CARBATTERY_13,CHARPORT_13,ELECTRIC_BIKE_MOD_13,CAMERA_MODX13
8,15,CDA,PR,84343564,CARBATTERY_15,CHARPORT_15,ELECTRIC_BIKE15,CAMERA_MOD_15
9,16,UA,S,9534534,CARBATTERY_16,CHARPORT_16,ELECTRIC_BIKE16,CAMERA_MOD_16
10,17,UOH,KOH,9845645,CARBATTERY_17,CHARPORT_17,ELECTRIC_BIKE17,CAMERA_MOD_17
11,18,YKA,OHM,9845643,CARBATTERY_18,CHARPORT_18,ELECTRIC_BIKE18,CAMERA_MOD_18
12,19,EGT,PY,9845642,CARBATTERY_19,CHARPORT_19,ELECTRIC_BIKE19,CAMERA_MOD_19
13,14,yk,MKK,3434453,CARBATTERY_14,CHAR_PORT14,ELECTRIC_BIKE_MOD_14,CAMERA_MODX14
14,1,hmdn,PRCS,7634363,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_13,CAMERA_MODX13
15,2,rj,lk,734343,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
16,3,ABDUL,JALEEL,43536649,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
17,3,rm,ly,734344,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
18,4,rq,fq,734341,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
19,6,aj,aq,734346,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2

#### Data Preprocessing.

In [386]:
def wrangle():
    # Reading the dataset.
    df = pd.read_csv('cars_dataset.csv')
    # Dropping the unwanted columns
    df.drop(columns=['Unnamed: 0'],inplace=True)
    return df

In [387]:
df = wrangle()

In [388]:
df

,customer_id,first_name,last_name,phone_num,item_1,item_2,item_3,item_4
0,5,rl,wl,734343,CARBATTERY_5,CHARPORT_5,ELECTRIC_BIKE_MOD_5,CAMERA_MODX5
1,7,ELN,TSA,3434453,CARBATTERY_7,CHARPORT_5,ELECTRIC_BIKE_MOD_7,CAMERA_MODX7
2,8,PUT,NN,3434452,CARBATTERY_8,CHARPORT_8,ELECTRIC_BIKE_MOD_8,CAMERA_MODX8
3,9,UKR,KGN,3434456,CARBATTERY_9,CHARPORT_9,ELECTRIC_BIKE_MOD_9,CAMERA_MODX9
4,10,GY,EU,3434456,CARBATTERY_10,CHARPORT_10,ELECTRIC_BIKE_MOD_10,CAMERA_MODX10
5,11,KS,A,3434451,CARBATTERY_11,CHARPORT_11,ELECTRIC_BIKE_MOD_11,CAMERA_MODX11
6,12,NG,AAF,3434452,CARBATTERY_12,CHARPORT_12,ELECTRIC_BIKE_MOD_12,CAMERA_MODX12
7,13,KK,MKK,3434453,CARBATTERY_13,CHARPORT_13,ELECTRIC_BIKE_MOD_13,CAMERA_MODX13
8,15,CDA,PR,84343564,CARBATTERY_15,CHARPORT_15,ELECTRIC_BIKE15,CAMERA_MOD_15
9,16,UA,S,9534534,CARBATTERY_16,CHARPORT_16,ELECTRIC_BIKE16,CAMERA_MOD_16
10,17,UOH,KOH,9845645,CARBATTERY_17,CHARPORT_17,ELECTRIC_BIKE17,CAMERA_MOD_17
11,18,YKA,OHM,9845643,CARBATTERY_18,CHARPORT_18,ELECTRIC_BIKE18,CAMERA_MOD_18
12,19,EGT,PY,9845642,CARBATTERY_19,CHARPORT_19,ELECTRIC_BIKE19,CAMERA_MOD_19
13,14,yk,MKK,3434453,CARBATTERY_14,CHAR_PORT14,ELECTRIC_BIKE_MOD_14,CAMERA_MODX14
14,1,hmdn,PRCS,7634363,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_13,CAMERA_MODX13
15,2,rj,lk,734343,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
16,3,ABDUL,JALEEL,43536649,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
17,3,rm,ly,734344,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
18,4,rq,fq,734341,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2
19,6,aj,aq,734346,CARBATTERY_13,CARBATTERY_13,ELECTRIC_BIKE_MOD_2,CAMERA_MODX2

In [389]:
# Selecting the specific column from the database.
X = df.drop(columns=['customer_id','first_name','last_name','phone_num'])

In [390]:
X

           item_1         item_2                item_3         item_4
0    CARBATTERY_5     CHARPORT_5   ELECTRIC_BIKE_MOD_5   CAMERA_MODX5
1    CARBATTERY_7     CHARPORT_5   ELECTRIC_BIKE_MOD_7   CAMERA_MODX7
2    CARBATTERY_8     CHARPORT_8   ELECTRIC_BIKE_MOD_8   CAMERA_MODX8
3    CARBATTERY_9     CHARPORT_9   ELECTRIC_BIKE_MOD_9   CAMERA_MODX9
4   CARBATTERY_10    CHARPORT_10  ELECTRIC_BIKE_MOD_10  CAMERA_MODX10
5   CARBATTERY_11    CHARPORT_11  ELECTRIC_BIKE_MOD_11  CAMERA_MODX11
6   CARBATTERY_12    CHARPORT_12  ELECTRIC_BIKE_MOD_12  CAMERA_MODX12
7   CARBATTERY_13    CHARPORT_13  ELECTRIC_BIKE_MOD_13  CAMERA_MODX13
8   CARBATTERY_15    CHARPORT_15       ELECTRIC_BIKE15  CAMERA_MOD_15
9   CARBATTERY_16    CHARPORT_16       ELECTRIC_BIKE16  CAMERA_MOD_16
10  CARBATTERY_17    CHARPORT_17       ELECTRIC_BIKE17  CAMERA_MOD_17
11  CARBATTERY_18    CHARPORT_18       ELECTRIC_BIKE18  CAMERA_MOD_18
12  CARBATTERY_19    CHARPORT_19       ELECTRIC_BIKE19  CAMERA_MOD_19
13  CARBATTERY_14    CHAR_PORT14  ELECTRIC_BIKE_MOD_14  CAMERA_MODX14
14  CARBATTERY_13  CARBATTERY_13  ELECTRIC_BIKE_MOD_13  CAMERA_MODX13
15  CARBATTERY_13  CARBATTERY_13   ELECTRIC_BIKE_MOD_2   CAMERA_MODX2
16  CARBATTERY_13  CARBATTERY_13   ELECTRIC_BIKE_MOD_2   CAMERA_MODX2
17  CARBATTERY_13  CARBATTERY_13   ELECTRIC_BIKE_MOD_2   CAMERA_MODX2
18  CARBATTERY_13  CARBATTERY_13   ELECTRIC_BIKE_MOD_2   CAMERA_MODX2
19  CARBATTERY_13  CARBATTERY_13   ELECTRIC_BIKE_MOD_2   CAMERA_MODX2

In [391]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   item_1  20 non-null     object
 1   item_2  20 non-null     object
 2   item_3  20 non-null     object
 3   item_4  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

# Build Model.

In [398]:
# Training the Apriori model on the dataset
from apriori_python import apriori

freqItemSet, rules = apriori([X], minSup=0.5, minConf=0.5)
print(rules)

[[{'item_3'}, {'item_4'}, 1.0], [{'item_4'}, {'item_3'}, 1.0], [{'item_2'}, {'item_4'}, 1.0], [{'item_4'}, {'item_2'}, 1.0], [{'item_2'}, {'item_1'}, 1.0], [{'item_1'}, {'item_2'}, 1.0], [{'item_3'}, {'item_1'}, 1.0], [{'item_1'}, {'item_3'}, 1.0], [{'item_4'}, {'item_1'}, 1.0], [{'item_1'}, {'item_4'}, 1.0], [{'item_3'}, {'item_2'}, 1.0], [{'item_2'}, {'item_3'}, 1.0], [{'item_3'}, {'item_2', 'item_1'}, 1.0], [{'item_2'}, {'item_3', 'item_1'}, 1.0], [{'item_1'}, {'item_3', 'item_2'}, 1.0], [{'item_3', 'item_2'}, {'item_1'}, 1.0], [{'item_3', 'item_1'}, {'item_2'}, 1.0], [{'item_2', 'item_1'}, {'item_3'}, 1.0], [{'item_2'}, {'item_4', 'item_1'}, 1.0], [{'item_4'}, {'item_2', 'item_1'}, 1.0], [{'item_1'}, {'item_2', 'item_4'}, 1.0], [{'item_2', 'item_4'}, {'item_1'}, 1.0], [{'item_2', 'item_1'}, {'item_4'}, 1.0], [{'item_4', 'item_1'}, {'item_2'}, 1.0], [{'item_3'}, {'item_2', 'item_4'}, 1.0], [{'item_2'}, {'item_3', 'item_4'}, 1.0], [{'item_4'}, {'item_3', 'item_2'}, 1.0], [{'item_3', 'item_2'}, {'item_4'}, 1.0], [{'item_3', 'item_4'}, {'item_2'}, 1.0], [{'item_2', 'item_4'}, {'item_3'}, 1.0], [{'item_3'}, {'item_4', 'item_1'}, 1.0], [{'item_4'}, {'item_3', 'item_1'}, 1.0], [{'item_1'}, {'item_3', 'item_4'}, 1.0], [{'item_3', 'item_4'}, {'item_1'}, 1.0], [{'item_3', 'item_1'}, {'item_4'}, 1.0], [{'item_4', 'item_1'}, {'item_3'}, 1.0], [{'item_3'}, {'item_2', 'item_4', 'item_1'}, 1.0], [{'item_2'}, {'item_3', 'item_4', 'item_1'}, 1.0], [{'item_4'}, {'item_3', 'item_2', 'item_1'}, 1.0], [{'item_1'}, {'item_3', 'item_2', 'item_4'}, 1.0], [{'item_3', 'item_2'}, {'item_4', 'item_1'}, 1.0], [{'item_3', 'item_4'}, {'item_2', 'item_1'}, 1.0], [{'item_3', 'item_1'}, {'item_2', 'item_4'}, 1.0], [{'item_2', 'item_4'}, {'item_3', 'item_1'}, 1.0], [{'item_2', 'item_1'}, {'item_3', 'item_4'}, 1.0], [{'item_4', 'item_1'}, {'item_3', 'item_2'}, 1.0], [{'item_3', 'item_2', 'item_4'}, {'item_1'}, 1.0], [{'item_3', 'item_2', 'item_1'}, {'item_4'}, 1.0], [{'item_3', 'item_4', 'item_1'}, {'item_2'}, 1.0], [{'item_2', 'item_4', 'item_1'}, {'item_3'}, 1.0]]

In [399]:
rules

[[{'item_3'}, {'item_4'}, 1.0],
 [{'item_4'}, {'item_3'}, 1.0],
 [{'item_2'}, {'item_4'}, 1.0],
 [{'item_4'}, {'item_2'}, 1.0],
 [{'item_2'}, {'item_1'}, 1.0],
 [{'item_1'}, {'item_2'}, 1.0],
 [{'item_3'}, {'item_1'}, 1.0],
 [{'item_1'}, {'item_3'}, 1.0],
 [{'item_4'}, {'item_1'}, 1.0],
 [{'item_1'}, {'item_4'}, 1.0],
 [{'item_3'}, {'item_2'}, 1.0],
 [{'item_2'}, {'item_3'}, 1.0],
 [{'item_3'}, {'item_1', 'item_2'}, 1.0],
 [{'item_2'}, {'item_1', 'item_3'}, 1.0],
 [{'item_1'}, {'item_2', 'item_3'}, 1.0],
 [{'item_2', 'item_3'}, {'item_1'}, 1.0],
 [{'item_1', 'item_3'}, {'item_2'}, 1.0],
 [{'item_1', 'item_2'}, {'item_3'}, 1.0],
 [{'item_2'}, {'item_1', 'item_4'}, 1.0],
 [{'item_4'}, {'item_1', 'item_2'}, 1.0],
 [{'item_1'}, {'item_2', 'item_4'}, 1.0],
 [{'item_2', 'item_4'}, {'item_1'}, 1.0],
 [{'item_1', 'item_2'}, {'item_4'}, 1.0],
 [{'item_1', 'item_4'}, {'item_2'}, 1.0],
 [{'item_3'}, {'item_2', 'item_4'}, 1.0],
 [{'item_2'}, {'item_3', 'item_4'}, 1.0],
 [{'item_4'}, {'item_2', 'item_3'}, 1.0],
 [{'item_2', 'item_3'}, {'item_4'}, 1.0],
 [{'item_3', 'item_4'}, {'item_2'}, 1.0],
 [{'item_2', 'item_4'}, {'item_3'}, 1.0],
 [{'item_3'}, {'item_1', 'item_4'}, 1.0],
 [{'item_4'}, {'item_1', 'item_3'}, 1.0],
 [{'item_1'}, {'item_3', 'item_4'}, 1.0],
 [{'item_3', 'item_4'}, {'item_1'}, 1.0],
 [{'item_1', 'item_3'}, {'item_4'}, 1.0],
 [{'item_1', 'item_4'}, {'item_3'}, 1.0],
 [{'item_3'}, {'item_1', 'item_2', 'item_4'}, 1.0],
 [{'item_2'}, {'item_1', 'item_3', 'item_4'}, 1.0],
 [{'item_4'}, {'item_1', 'item_2', 'item_3'}, 1.0],
 [{'item_1'}, {'item_2', 'item_3', 'item_4'}, 1.0],
 [{'item_2', 'item_3'}, {'item_1', 'item_4'}, 1.0],
 [{'item_3', 'item_4'}, {'item_1', 'item_2'}, 1.0],
 [{'item_1', 'item_3'}, {'item_2', 'item_4'}, 1.0],
 [{'item_2', 'item_4'}, {'item_1', 'item_3'}, 1.0],
 [{'item_1', 'item_2'}, {'item_3', 'item_4'}, 1.0],
 [{'item_1', 'item_4'}, {'item_2', 'item_3'}, 1.0],
 [{'item_2', 'item_3', 'item_4'}, {'item_1'}, 1.0],
 [{'item_1', 'item_2', 'item_3'}, {'item_4'}, 1.0],
 [{'item_1', 'item_3', 'item_4'}, {'item_2'}, 1.0],
 [{'item_1', 'item_2', 'item_4'}, {'item_3'}, 1.0]]

In [400]:
transactions = []
for i in range(0, 19):
    transactions.append([str(X.values[i,j]) for j in range(0, 3)])

# Training the Apriori model on the dataset
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

## Displaying the first results coming directly from the output of the apriori function
results = list(rules)
results

## Putting the results well organised into a Pandas DataFrame
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [401]:
## Displaying the results non sorted
resultsinDataFrame

## Displaying the results sorted by descending lifts
resultsinDataFrame.nlargest(n = 42, columns = 'Lift')

   Left Hand Side       Right Hand Side   Support  Confidence       Lift
0   CARBATTERY_10           CHARPORT_10  0.052632    1.000000  19.000000
1   CARBATTERY_10  ELECTRIC_BIKE_MOD_10  0.052632    1.000000  19.000000
2   CARBATTERY_11           CHARPORT_11  0.052632    1.000000  19.000000
3   CARBATTERY_11  ELECTRIC_BIKE_MOD_11  0.052632    1.000000  19.000000
4   CARBATTERY_12           CHARPORT_12  0.052632    1.000000  19.000000
5   CARBATTERY_12  ELECTRIC_BIKE_MOD_12  0.052632    1.000000  19.000000
9   CARBATTERY_14           CHAR_PORT14  0.052632    1.000000  19.000000
10  CARBATTERY_14  ELECTRIC_BIKE_MOD_14  0.052632    1.000000  19.000000
11  CARBATTERY_15           CHARPORT_15  0.052632    1.000000  19.000000
12  CARBATTERY_15       ELECTRIC_BIKE15  0.052632    1.000000  19.000000
13  CARBATTERY_16           CHARPORT_16  0.052632    1.000000  19.000000
14  CARBATTERY_16       ELECTRIC_BIKE16  0.052632    1.000000  19.000000
15  CARBATTERY_17           CHARPORT_17  0.052632    1.000000  19.000000
16  CARBATTERY_17       ELECTRIC_BIKE17  0.052632    1.000000  19.000000
17  CARBATTERY_18           CHARPORT_18  0.052632    1.000000  19.000000
18  CARBATTERY_18       ELECTRIC_BIKE18  0.052632    1.000000  19.000000
19  CARBATTERY_19           CHARPORT_19  0.052632    1.000000  19.000000
20  CARBATTERY_19       ELECTRIC_BIKE19  0.052632    1.000000  19.000000
22   CARBATTERY_5   ELECTRIC_BIKE_MOD_5  0.052632    1.000000  19.000000
24   CARBATTERY_7   ELECTRIC_BIKE_MOD_7  0.052632    1.000000  19.000000
25   CARBATTERY_8            CHARPORT_8  0.052632    1.000000  19.000000
26   CARBATTERY_8   ELECTRIC_BIKE_MOD_8  0.052632    1.000000  19.000000
27   CARBATTERY_9            CHARPORT_9  0.052632    1.000000  19.000000
28   CARBATTERY_9   ELECTRIC_BIKE_MOD_9  0.052632    1.000000  19.000000
29    CHARPORT_10  ELECTRIC_BIKE_MOD_10  0.052632    1.000000  19.000000
30    CHARPORT_11  ELECTRIC_BIKE_MOD_11  0.052632    1.000000  19.000000
31    CHARPORT_12  ELECTRIC_BIKE_MOD_12  0.052632    1.000000  19.000000
33    CHARPORT_15       ELECTRIC_BIKE15  0.052632    1.000000  19.000000
34    CHARPORT_16       ELECTRIC_BIKE16  0.052632    1.000000  19.000000
35    CHARPORT_17       ELECTRIC_BIKE17  0.052632    1.000000  19.000000
36    CHARPORT_18       ELECTRIC_BIKE18  0.052632    1.000000  19.000000
37    CHARPORT_19       ELECTRIC_BIKE19  0.052632    1.000000  19.000000
40     CHARPORT_8   ELECTRIC_BIKE_MOD_8  0.052632    1.000000  19.000000
41     CHARPORT_9   ELECTRIC_BIKE_MOD_9  0.052632    1.000000  19.000000
42    CHAR_PORT14  ELECTRIC_BIKE_MOD_14  0.052632    1.000000  19.000000
21   CARBATTERY_5            CHARPORT_5  0.052632    1.000000   9.500000
23   CARBATTERY_7            CHARPORT_5  0.052632    1.000000   9.500000
32    CHARPORT_13  ELECTRIC_BIKE_MOD_13  0.052632    1.000000   9.500000
38     CHARPORT_5   ELECTRIC_BIKE_MOD_5  0.052632    0.500000   9.500000
39     CHARPORT_5   ELECTRIC_BIKE_MOD_7  0.052632    0.500000   9.500000
6     CHARPORT_13         CARBATTERY_13  0.052632    1.000000   3.166667
7   CARBATTERY_13  ELECTRIC_BIKE_MOD_13  0.105263    0.333333   3.166667

# Communicate Results.